/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PuikAccordion: typeof import('@prestashopcorp/puik/es')['PuikAccordion']
    PuikAccordionGroup: typeof import('@prestashopcorp/puik/es')['PuikAccordionGroup']
    PuikBreadcrumb: typeof import('@prestashopcorp/puik/es')['PuikBreadcrumb']
    PuikButton: typeof import('@prestashopcorp/puik/es')['PuikButton']
    PuikCheckbox: typeof import('@prestashopcorp/puik/es')['PuikCheckbox']
    PuikMenu: typeof import('@prestashopcorp/puik/es')['PuikMenu']
    PuikMenuItem: typeof import('@prestashopcorp/puik/es')['PuikMenuItem']
    PuikMenuItemSeparator: typeof import('@prestashopcorp/puik/es')['PuikMenuItemSeparator']
    PuikMenuItemTitle: typeof import('@prestashopcorp/puik/es')['PuikMenuItemTitle']
    PuikProgressBar: typeof import('@prestashopcorp/puik/es')['PuikProgressBar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
